# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: "就这样&巴"
subtitle: '个人网志'
description: '该博客由作者于大学期间基于Hexo框架搭建，主要用于记录网络技术领域的学习笔记和一些莫名其妙的小项目。作者非计算机专业出身，所写内容均为个人想法，仅为读者提供参考思路。内容多源于个人想法和身边朋友的问题，旨在交流分享，请各位读者结合自身需求理性借鉴。'
keywords:
  - Hexo
  - 博客
  - 技术
  - 笔记
  - 随想
  - 编程

author: "Shangjhih Jhao"
language: zh-CN
timezone: 'Asia/Shanghai'
about: "  这是一个使用 Hexo 搭建的个人博客。作者在大学期间创建，非计算机专业。  所写内容仅供参考，可能存在错误或不严谨之处。"



# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://lvshuqi.top
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
syntax_highlighter: highlight.js
highlight:
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 1
  order_by: -date
  
# 归档页每页显示10篇文章
archive_generator:
  per_page: 10
  yearly: true
  monthly: true


# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 1
pagination_dir: page 

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
# theme: landscape
#theme: next
theme: next


# reading timer
symbols_count_time:
  symbols: true
  time: true
  total_symbols: true
  total_time: true
  exclude_codeblock: false
  awl: 3
  wpm: 200
  suffix: "mins."

# 文章排序
#index_generator:
 # path: ''
 # per_page: 1
  #order_by: -date  # 按时间倒序排列

menu:
  home: /
  about: /about
  categies: /categories
  tags: /tags
  archives: /archives

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repo: git@github.com:Shangjhih/Shangjhih.github.io.git
  branch: master
  cname: true